name: LkCa15

out_base: output/

gas: true
species : 12CO # Possible choices: 12CO, 13CO, C18O. Future may include HCN, etc...
transition: 3-2 # J =

grid:
  nr: 128
  ntheta: 64 # if mirrored about the equator, total of 64
  nphi: 1
  r_in: 0.1 # [AU] # Inner edge of model grid
  r_out: 2000. # [AU] # Outer edge of model grid

# Are there any channels of the dataset to exclude? If so, provide them here, indexed from 1.
# exclude: [35, 36, 37, 38]

# Distance prior setup
fix_d : true

dpc_prior:
  mu : 145.
  sig : 20.

# What type of model will we be fitting? This also affects which parameters to include.
model : standard # choices of {standard, truncated, vertical, cavity, etc..}

# parameters, either used for model synthesis or visualization. Be careful that all of these are Float64 and not Int
parameters:
  M_star: 1.11 # [M_sun] stellar mass
  r_c: 470.50 # [AU] characteristic radius
  T_10: 94.85 # [K] temperature at 10 AU
  q: 0.57 # temperature gradient exponent
  gamma: 1.0 # surface density gradient
  logM_gas: -3.87 # [M_Sun] disk mass of gas
  ksi: 0.48 # [km/s] microturbulence
  dpc: 154. # [pc] distance
  incl: 45.7 # [degrees] inclination
  PA: 153.2 # [degrees] position angle
  vel: -1.984 # [km/s]
  mu_RA: 0.334 # [arcsec] centroid location
  mu_DEC: -0.299 # [arcsec]

# The HDF5 file containing the visibilities
data_file: data.hdf5

# Image setup
size_arcsec: 70.0 # [arcsec]
npix: 512

# Starting positions of walkers
pos0: pos0.npy

# MCMC setup
samples: 10
loops: 50

emulator:
  parameters: ["nu", "incl"]
  ranges:
    nu: [345.7956, 345.7975] # GHz
    incl: [35, 55] # Degrees

# Some parameters that may be helpful for making more realistic channel map plots of the model.
# You will likely need to change these to correspond to the parameters of your observation.
beam :
  rms : 0.1 # Jy/beam
  BMAJ: 0.9 # arcsec
  BMIN: 0.9 # arcsec
  BPA: 1.0 # degrees east of North of the semi-major axis.
